version: '3.4'

services:
  apigateway:
    image: wl_apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5100:80"
    depends_on:
      - user-mic
      - task-mic

  user-mic:
    image: wl_usermic
    ports:
      - "5101:80"

  task-mic:
    image: wl_taskmic
    ports:
      - "5102:80"
